using System.Text;

namespace OpenglLib
{
    public static class GeneratorConst
    {
        public const string LABLE = "Rep.g";

        private static string projectNamespace = "UserScripts";

        public static string GetDefaultNamespaces()
        {
            var defaultNamespace = 
@$"using System.Collections.Generic;
using System.Numerics;
using Silk.NET.Maths;
using AtomEngine;
using EngineLib;
using OpenglLib;
using System;";
            if (!string.IsNullOrWhiteSpace(projectNamespace))
            {
                defaultNamespace += $"\nusing {projectNamespace};";
            }
            return defaultNamespace;
        }

        public static void SetUserScriptNamespace(string @namespace)
        {
            //"using UserScriptNamespace;"
            projectNamespace = @namespace;
        }

        public static string GetUserScriptNamespace()
        {
            return $"namespace {projectNamespace}";
        }

        public static void WriteGeneratedCodeHeader(StringBuilder builder, string sourceGuid)
        {
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// This code was generated. Dont change this code.");
            builder.AppendLine($"// SourceGuid: {sourceGuid ?? "Unknown"}");
            builder.AppendLine($"// GeneratedAt: {DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss")} UTC");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
        }

    }
}
