using EngineLib;
using System.Text;
using System;

namespace Editor
{
    public static class GeneratorConst
    {
        public static string GetDefaultNamespaces()
        {
            var projConfig = ServiceHub.Get<Configuration>().GetConfiguration<ProjectConfigurations>(ConfigurationSource.ProjectConfigs);
            return
@$"using System.Collections.Generic;
using System.Numerics;
using Silk.NET.Maths;
using AtomEngine;
using EngineLib;
using OpenglLib;
using System;
using {projConfig.RootNamespace};";
        }

        public static string GetUserScriptNamespace()
        {
            var projConfig = ServiceHub.Get<Configuration>().GetConfiguration<ProjectConfigurations>(ConfigurationSource.ProjectConfigs);
            return $"namespace {projConfig.RootNamespace}";
        }

        public static void WriteGeneratedCodeHeader(StringBuilder builder, string sourceGuid)
        {
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// This code was generated. Dont change this code.");
            builder.AppendLine($"// SourceGuid: {sourceGuid ?? "Unknown"}");
            builder.AppendLine($"// GeneratedAt: {DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss")} UTC");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
        }

    }
}
